// <auto-generated />
using System;
using Desafio_Desenvolvimento.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_Desenvolvimento.Infra.Data.Migrations
{
    [DbContext(typeof(DesafioDbContext))]
    partial class DesafioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Desafio_Desenvolvimento.Domain.Entities.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DataVisualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MunicipioCodigo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Npu")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.HasIndex("Npu")
                        .IsUnique();

                    b.ToTable("Processos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8ba3812f-f5a0-4665-b967-50b7edb11f26"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2673),
                            Municipio = "São Paulo",
                            MunicipioCodigo = 3550308,
                            Nome = "Ação de Indenização por Danos Morais",
                            Npu = "000001-23.2023.8.26.0100",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("e0febb8d-ae63-4661-871e-d57dee75f84a"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2683),
                            Municipio = "São Paulo",
                            MunicipioCodigo = 3550308,
                            Nome = "Ação de Cobrança de Aluguéis Atrasados",
                            Npu = "000002-45.2023.8.26.0100",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("82276992-1b8a-40ef-960b-8444eb008433"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2684),
                            Municipio = "São Paulo",
                            MunicipioCodigo = 3550308,
                            Nome = "Ação de Rescisão Contratual",
                            Npu = "000003-67.2023.8.26.0100",
                            UF = "SP"
                        },
                        new
                        {
                            Id = new Guid("aaa8fa0d-1ddd-4a8e-834b-c268d2abdea8"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2693),
                            Municipio = "Rio de Janeiro",
                            MunicipioCodigo = 3304557,
                            Nome = "Divórcio Consensual",
                            Npu = "000004-89.2023.8.19.0001",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("143252d2-4a3a-429d-9626-487065c12687"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2694),
                            Municipio = "Rio de Janeiro",
                            MunicipioCodigo = 3304557,
                            Nome = "Ação de Execução Fiscal",
                            Npu = "000005-12.2023.8.19.0001",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("d5b7baab-c719-4f6e-9811-10d8fa4825e0"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2695),
                            Municipio = "Rio de Janeiro",
                            MunicipioCodigo = 3304557,
                            Nome = "Ação de Inventário e Partilha",
                            Npu = "000006-34.2023.8.19.0001",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = new Guid("c9d1d385-0b0f-4063-8194-dac2103e766b"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2696),
                            Municipio = "Curitiba",
                            MunicipioCodigo = 4106902,
                            Nome = "Ação de Cobrança de Condomínio",
                            Npu = "000007-56.2023.8.16.0001",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("da2a6800-edb4-4545-adf6-780b7579998b"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2697),
                            Municipio = "Curitiba",
                            MunicipioCodigo = 4106902,
                            Nome = "Mandado de Segurança",
                            Npu = "000008-78.2023.8.16.0001",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("24d9d30f-707f-44f2-8694-3fec03ac2a7d"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2698),
                            Municipio = "Curitiba",
                            MunicipioCodigo = 4106902,
                            Nome = "Ação de Usucapião",
                            Npu = "000009-90.2023.8.16.0001",
                            UF = "PR"
                        },
                        new
                        {
                            Id = new Guid("69931674-41a3-4abc-a9fd-af82a652cb19"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2699),
                            Municipio = "Cuiabá",
                            MunicipioCodigo = 5103403,
                            Nome = "Ação de Alvará Judicial",
                            Npu = "000010-12.2023.8.11.0002",
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("f4f6413c-f1f8-4c10-9384-b1154395759f"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2700),
                            Municipio = "Cuiabá",
                            MunicipioCodigo = 5103403,
                            Nome = "Ação de Interdição",
                            Npu = "000011-34.2023.8.11.0002",
                            UF = "MT"
                        },
                        new
                        {
                            Id = new Guid("9e64182a-9ec3-42a9-acd7-5e51896c84fb"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2703),
                            Municipio = "Belo Horizonte",
                            MunicipioCodigo = 3106200,
                            Nome = "Ação Trabalhista por Verbas Rescisórias",
                            Npu = "000012-56.2023.5.03.0001",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("ef66202b-a916-4953-b22b-38e480ed6642"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2703),
                            Municipio = "Belo Horizonte",
                            MunicipioCodigo = 3106200,
                            Nome = "Ação de Reintegração de Posse",
                            Npu = "000013-78.2023.8.13.0001",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("b5798b2c-3f15-438a-a885-4b923ffabd14"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2704),
                            Municipio = "Belo Horizonte",
                            MunicipioCodigo = 3106200,
                            Nome = "Ação de Divórcio Litigioso",
                            Npu = "000014-90.2023.8.13.0001",
                            UF = "MG"
                        },
                        new
                        {
                            Id = new Guid("036b37a4-cc0b-4db3-89d5-8a9a55f5a191"),
                            DataCadastro = new DateTime(2024, 10, 8, 23, 1, 9, 694, DateTimeKind.Local).AddTicks(2705),
                            Municipio = "Fortaleza",
                            MunicipioCodigo = 2304400,
                            Nome = "Ação de Alimentos",
                            Npu = "000015-23.2023.8.06.0001",
                            UF = "CE"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
